### ISSUE TITLE
CI build steps

### ISSUE THREAD

**Issue by wvanbergen** [Shopify/sarama#190]
- [x] `go fmt` - see #196
- [x] `go vet` - see #195 - requires dropping support for go 1.1
- [x] `go lint` - see #194 for initial fixes.
- [x] `errcheck` - requires some fixes to `Broker.Open` calls
- [x] `go test -race` - see #189

@eapache

**Comment by wvanbergen** [comment]
We tackled all the golint suggestions we want to fi. Because there's many suggestions that we're not willing to tackle, we should not make it part of CI, but just run it every now and then. Closing this.
